[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# Required for Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Uncomment this if you want to use Netlify Functions for your backend
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200 