[build]
  base = "frontend"
  command = "npm install @netlify/plugin-nextjs@4.42.2 && npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF frontend/"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_USE_NETLIFY_EDGE = "true"

[functions]
  directory = "../netlify/functions"
  node_bundler = "esbuild"

# API function redirects
[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/leads"
  to = "/.netlify/functions/leads"
  status = 200

[[redirects]]
  from = "/api/leads/*"
  to = "/.netlify/functions/leads/:splat"
  status = 200

[[redirects]]
  from = "/api/companies"
  to = "/.netlify/functions/companies"
  status = 200

[[redirects]]
  from = "/api/companies/*"
  to = "/.netlify/functions/companies/:splat"
  status = 200

[[redirects]]
  from = "/api/interactions"
  to = "/.netlify/functions/interactions"
  status = 200

[[redirects]]
  from = "/api/interactions/*"
  to = "/.netlify/functions/interactions/:splat"
  status = 200

[[redirects]]
  from = "/api/deals"
  to = "/.netlify/functions/deals"
  status = 200

[[redirects]]
  from = "/api/deals/*"
  to = "/.netlify/functions/deals/:splat"
  status = 200

[[redirects]]
  from = "/api/tasks"
  to = "/.netlify/functions/tasks"
  status = 200

[[redirects]]
  from = "/api/tasks/*"
  to = "/.netlify/functions/tasks/:splat"
  status = 200

# NextJS redirects (Must be last)
[[plugins]]
  package = "@netlify/plugin-nextjs" 